name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  all:
    name: Build, Release, and Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Backend
        run: |
          rustup update stable
          cargo build --release
        working-directory: api
        
      - name: Build Extension
        uses: oven-sh/setup-bun@v2
      - run: |
          bun install
          bun run build
        working-directory: extension
        
      - name: Package and Release
        run: |
          cd extension/dist && zip -r ../../linkman-extension-${{ github.ref_name }}.zip .
          
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            api/target/release/api
            linkman-extension-${{ github.ref_name }}.zip
          draft: false
          prerelease: false

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.ref_name }}
